### ISSUE TITLE
Complex Color Maps

### ISSUE THREAD

**Issue by retostauffer** [retostauffer/python-colorspace#1]
The more complex `divergingx_hcl` and `sequentialx_hcl` palettes are not yet implemented. Should be added in the near future.

**Comment by zeileis** [comment]
The `divergingx_hcl` class is implemented now: https://retostauffer.github.io/python-colorspace/man/colorspace.palettes.divergingx_hcl.html

`sequentialx_hcl` is not a thing (also not in the R package).
