### ISSUE TITLE
Extend GPL license

### ISSUE THREAD

**Issue by zeileis** [retostauffer/python-colorspace#12]
Currently the LICENSE just includes the GPL version 2. I think we should also allow GPL version 3 which will make it a lot easier to combine `colorspace` snippets with other code under different licenses that are compatible with the GPL-3 but not GPL-2.

This can be done by either explicitly saying the both version 2 or version 3 are allowed or by allow GPL-2 or any later version. Currently, both are equivalent but the later would include potential updated versions of the GPL as well.

**Comment by retostauffer** [comment]
@zeileis thanks for the web touch-ups (https://github.com/retostauffer/python-colorspace/pull/11). I have adjusted the license and uploaded a test version (`0.4.3.1`) of our package to the PyPI test server.

* URL: <https://test.pypi.org/project/colorspace/0.4.3.1/>

### Logo

The logo (from `README.md`) looks great there! :)

### License

Shown under [Meta](https://test.pypi.org/project/colorspace/0.4.3.1/) in the left navbar. Currently I am explicitly listing GPL-2 and GPL-2 (not GPL-2+/GPL-3+).

> License: GNU General Public License v2 (GPLv2), GNU General Public License v3 (GPLv3) (GPL-2 | GPL-3)

We can easily allow for "GPL-2 or later" and "GPL-3 or later" by changing the `classifiers` in [`setup.py`](https://github.com/retostauffer/python-colorspace/blob/main/setup.py) to "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)" and/or "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)" (pre-defined strings, [see here](https://pypi.org/classifiers/)).

**Comment by zeileis** [comment]
Cool, the logo looks really nice!

Thanks also for the pointer to `setup.py`. I made a few further improvements and updates in this PR: https://github.com/retostauffer/python-colorspace/pull/14

**Comment by retostauffer** [comment]
Perfect; thanks @zeileis (btw, no need to respond over the weekend, I am just trying to get stuff done).

I assume we stick to GPL-2 | GPL-3 (without "or later") for now? If so, please just close this issue.
