### ISSUE TITLE
Customized sqtuential_hcl doing some honky-wonky

### ISSUE THREAD

**Issue by retostauffer** [retostauffer/python-colorspace#19]
@retostauffer , the last example where only changing chroma is donig something strange; might be related to `cmax`; check and fix.

```
from colorspace import palette, sequential_hcl, swatchplot

H = palette(sequential_hcl(h = [0, 300], c = [60, 60], l = 65).colors(5), "Hue")
C = palette(sequential_hcl(h = 0, c = [0, 100], l = 65).colors(5), "Chroma")
L = palette(sequential_hcl(h = 0, c = 0, l = [90, 25]).colors(5), "Luminance")

swatchplot([H, C, L], figsize = (5, 1.5));
```

**Comment by zeileis** [comment]
Hopefully fixed now by extracting `cmax` correctly in `sequential_hcl`. Tweaked settings of example to match the settings used in R.

**Comment by retostauffer** [comment]
Prefect, thanks for the quick fix @zeileis . Made one small adjustment in the docstring (`` were missing) but functionality restored, so I am closing this one now.
