### ISSUE TITLE
Custom palette tests fail on Windows

### ISSUE THREAD

**Issue by hollowscene** [retostauffer/python-colorspace#21]
Five tests fail in `test_palettes_custom_palconfig_files.py` when test suite is run on Windows.

Here is the full pytest output: [pytest_results.txt](https://github.com/user-attachments/files/16918444/pytest_results.txt)

For quick access, the error message of one of those test fails:

```
___________________________________ test_hclpalettes_custom_palconfig_good_custom_div ___________________________________ 

    def test_hclpalettes_custom_palconfig_good_custom_div():

        tmpfile = NamedTemporaryFile()
>       with open(tmpfile.name, "w") as fid: fid.write(good_custom_div)
E       PermissionError: [Errno 13] Permission denied: 'C:\\Users\\andrew\\AppData\\Local\\Temp\\tmpmchuptx8'
```

This appears to be an OS difference caused by the tempfile package. [Old but relevant StackOverflow answer](https://stackoverflow.com/a/3924253).

**Comment by retostauffer** [comment]
Dear @hollowscene 

thank you for pointing this out and providing a pull request to resolve this issue. We have merged your PR (https://github.com/retostauffer/python-colorspace/pull/22) and successfully ran all tests on both, Windows and Linux. 

Some more details can be found here: https://github.com/retostauffer/python-colorspace/pull/22#issuecomment-2396264315

**Comment by retostauffer** [comment]
Many thanks again @hollowscene for [reviewing our submission](https://github.com/openjournals/joss-reviews/issues/7120) to [The Open Source Journal](https://https://joss.theoj.org/).

Your bug report and PR (#22) were greatly appreciated! I’ll be closing the issue at this time.
