### ISSUE TITLE
Fix apostrophes rendered as \u2019

### ISSUE THREAD

**Issue by slel** [retostauffer/python-colorspace#5]
Two instance of "Let's" and one instance of "let's" on the page

- https://python-colorspace.readthedocs.io/en/latest/examples/usageexamples.html

appear as "Let\u2019s" and "let\u2019s" instead.

Of course the unicode character 2019 is "right single quote mark".

But actual apostrophes or right single quote marks
would be more readable than a unicode escape code.

**Comment by retostauffer** [comment]
Thanks a lot for pointing this out. Over the last two weeks I found some time to work on this package again. This includes revamping the entire documentation and extend the features. Thus, I'll not fix the current version and try to invest the time in getting the updates ready some when soon.

All best,
R

**Comment by zeileis** [comment]
The new documentation produced via [Quarto](https://quarto.org) is now available at <https://retostauffer.github.io/python-colorspace/> and does not seem to have these problems anymore. Closing this here.
