### ISSUE TITLE
Suggestion on showing colours in Jupyter notebooks 

### ISSUE THREAD

**Issue by matteoferla** [retostauffer/python-colorspace#7]
This is a great module and I wanted to suggest an **enhancement**.
In Jupyter Notebooks, an instance of an object is displayed (via IPython.display.display) in HTML according to the class `_repr_html_` (and `__repr__` as a fallback). As a result one can play with the styles attribute of an element say colouring text (`color` or the fill `background`).

```python3
from colorspace.colorlib import HCL, hexcols, colorobject
from copy import copy

def _repr_html_(self):
    zelf = copy(self)
    zelf.to('hex')
    colhexes = zelf.colors()
    styles= {'height': '50px',
             'width':'50px',
             'border':'5px solid grey',
             'border-top':'5px solid white', # get some Helmholtz–Kohlrausch effect action!
             'border-bottom':'5px solid black',
            }
    dict2style = lambda d: ';'.join(map(':'.join, d.items()))
    # jupyter runs off bootstrap-3 formatting
    divs = [f'<div class="col-md-1" style="{dict2style(styles)}; background:{colhex}"></div>' for colhex in colhexes]
    return '<div class="row">{inner}</div>'.format(inner=''.join(divs))

colorobject._repr_html_ = _repr_html_
hexcols(['#002147', '#F3AD5B', '#F7601E'])
```
![Screenshot 2022-01-13 at 13 45 25](https://user-images.githubusercontent.com/11302983/149341478-0012ce8a-9ca0-43fc-a3d1-822aa7fa2ed3.png)

**EDIT.** This affects the behaviour of `IPython.display.display(object)` or the last object returned in the cells (`_`), not `print(object)`, which still preferentially runs off `__str__()`

**Comment by retostauffer** [comment]
Dear @matteoferla 

apologies for not responding at all, not had a lot of time to bring the project further over the past months. We've just made a [(pre-)release](https://pypi.org/project/colorspace/) of the [colorspace](https://pypi.org/project/colorspace/) package on PyPI, revamped the [documentation](https://retostauffer.github.io/python-colorspace/), and are working on implementing the last missing bits and pieces.

Thanks for the suggestion, I have implemented your idea for the `hexcols` object (for testing). Examples on how this looks can be found here:

* [hexcols] man page; Examples section

@zeileis this could be, as suggested by @matteoferla, be implemented for all color objects and palettes we provide. Advantage: looks nice in the rendered jupyter/qmd HTMLs, but 'hides' the coordinates of the different color spaces. See [`cols.to("CIEXYZ")`](https://retostauffer.github.io/python-colorspace/) output (Examples). What are your first thoughts on this?

**Comment by zeileis** [comment]
This is really neat, thank you both!

As for your question, Reto, I'm not quite sure what you mean. If I understand it correctly you could apply `hexcols()` to any hex vector, couldn't you? Or do you mean that we should make this the default return value?

If the latter, then I would prefer that users have to ask explicitly for it, rather than getting it by default. Or possibly one could provide an argument for this?

**Comment by retostauffer** [comment]
@zeileis the latter. Each object should have a `__repr__` (stdout representation) and can have a `_repr_html_`. The latter is only used when rendering via jupyter. 

## hexcols

So far, the `hexcols`  output always looked as follows:

```
In [2]: hexcols(["#00ff00", "#ff00ff", "#0000ff"])
Out[2]: 
hexcols color object (3 colors)
        hex_
  1:b'#00ff00'
    b'#ff00ff'
    b'#0000ff'
```

... which is still the standard representation (`__repr__`) and is also explicitly used when one uses `print(<object>)`. When included in a jupyter notebook (or, in our case quarto document) the standard output for `hexcols` is now this html swatch.

## Other objects

We _could_ make this the default jupyter output for other objects as well (like e.g., `CIEXYZ`, `polarLUV`), but then the user would see a HTML hex color swatch, whilst currently the user sees the coordinates of the colors. Also when included in a jupyter notebook or quarto. E.g.,:

```
polarLUV color object (3 colors)
           H       C       L
  1:  127.72  135.78   87.74
      307.73  137.40   60.32
      265.87  130.68   32.30
```

Not sure if that made everything more clear; we can also talk next time we see each other :).

**Comment by retostauffer** [comment]
Thanks @zeileis, fully agree. For now, `_repr_html_` would also create an HTML swatch for an infinite number of colors. I will add restriction (only if number of colors < `A`; 5-10 colors are easily possible) and think of a way to be able to an HTML swatch for more than `A` colors (maybe 10-30). 

For all other objects we will stick to the standard representation showing the coordinates.

**Comment by zeileis** [comment]
Hmm, my gut feeling is that I would not discriminate based on the length. Showing a long hexcols vector will not be very useful either way. So you might as well be consistent and use the same kind of output.

**Comment by retostauffer** [comment]
Agree, I consider this as 'done'. Only implemented for `hexcolor` colorobjects, and same behavior for any number of colors.

I consider this done for now, and thanks again to for the suggestion!
