### ISSUE TITLE
Provided pip install command is wrong on GH pages

### ISSUE THREAD

**Issue by jangler** [retostauffer/python-colorspace#8]
It should be `pip install git+https://github.com/retostauffer/python-colorspace.git`, not `pip install https://github.com/retostauffer/python-colorspace`. Otherwise the command fails with an error.

**Comment by avanavana** [comment]
+1

Just wanted to say that I also discovered this in my attempts to use this module in a Jupyter Lab notebook running in a conda environment.

Also, for those also trying to use this (or other modules on Github) in such a conda-based Jupyter lab/notebook setting—note that given all the potential hangups documented with using pip and conda together, your best bet is to simply run the magic command `%pip install git+https://github.com/retostauffer/python-colorspace.git` right in your notebook.  Works like a charm.

**Comment by zeileis** [comment]
Thanks for reporting this. The problem has been fixed in the new documentation page: <https://retostauffer.github.io/python-colorspace/installation.html>

Finally, the current version of the package is also available from PyPI at <https://pypi.org/project/colorspace/>.
